### ISSUE TITLE
Use difflib instead of length to detect changes

### ISSUE THREAD

**Issue by coveritytest** [muety/website-watcher#17]
Currently you only register changes that result in a change of the length of the HTML source code. But it could happen that additions and deletions sum out at 0 which leads to a false positive. Also you don't register changes from Test to test. Do you consider using difflib instead? Would also have the benefit, that you could send the diff with the mail, instead of just a link to the URL.

**Comment by muety** [comment]
Great idea! I wasn't aware of [difflib](https://docs.python.org/3.8/library/difflib.html) and that it's even part of the standard library. I'll adopt it as soon as possible.

This project started out as a very baisc, hacky script and the "change detection" logic wasn't changed since then. Now it's time to become a little more mature.

**Comment by coveritytest** [comment]
Kudos for the quick implementation, I think there is a bug though. doc1 and doc2 are different, although the HTML source code didn't change. For example umlauts are treated differently, so are CRLF: [see](https://ibb.co/k9Fzj3q).

**Comment by coveritytest** [comment]
Unfortunately, there's still some issue with the encoding. The content read from the file differs from the one it gets via requests. Not sure where and why, though.

**Comment by muety** [comment]
I'll look into it again these days!

**Comment by muety** [comment]
Please try again.

**Comment by coveritytest** [comment]
Perfect, that was the problem. Thanks!
